sudo: required
services: 
  - docker

before_install:
  - docker build -t shiru1104/docker-react -f Dockerfile .

script:
  - docker run -e CI=true shiru1104/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-1-879687266632"
  bucket_path: "docker-react" 
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
    
